Main.class: Main.java ColorPickerGUI.class PaintGUI.class LoginGUI.class Colour.class Canvas.class Admin.class User.class HEX.class RGB.class HSV.class
	javac -g Main.java

ColorPickerGUI.class: ColorPickerGUI.java
	javac -g ColorPickerGUI.java

PaintGUI.class: PaintGUI.java
	javac -g PaintGUI.java

LoginGUI.class: LoginGUI.java
	javac -g LoginGUI.java

Colour.class: Colour.java
	javac -g Colour.java

Canvas.class: Canvas.java
	javac -g Canvas.java

Admin.class: Admin.java
	javac -g Admin.java

User.class: User.java
	javac -g User.java

HEX.class: HEX.java
	javac -g HEX.java

RGB.class: RGB.java
	javac -g RGB.java

HSV.class: HSV.java
	javac -g HSV.java

run: Main.class
	java Main

clean:
	rm *.class
	rm *.ser

debug: Main.class
	jdb Main


